### ISSUE TITLE
Bad Request errors on SetAsync

### ISSUE THREAD

**Issue by guidojw** [nkpetko/RbxDataStoreService#11]
I'm getting Bad Request errors on using DataStore.SetAsync, something about the data length:

```sh
[
  {
    code: 6,
    message: 'The provided data length does not match the amount of data.',
    userFacingMessage: 'Something went wrong'
  }
]
```
The value is pretty long, the request that was sent for this SetAsync has `valueLength=5361` in it.

What could be the problem here?

**Comment by nkpetko** [comment]
Hmmm, what the hell, I have no clue wtf is happening, could you try debug it and find the true length of the data, and compare it to the value length and get back to me?

**Comment by nkpetko** [comment]
It will most likely get fixed in the next revision, if you find anymore issues like this, please leave them under this issue.

**Comment by nkpetko** [comment]
Okay well it was simply a fuck-up on Roblox's part, the way they read data via form-url encoded on the gamepersistence api is quite broken, it was fixed /v1/persistence/* and with the better addition of parsing legacy with json.

**Comment by guidojw** [comment]
Coincidence lol, I literally just started trying to intercept requests from Studio with Postman to see if/what your module is doing wrong.

Okay interesting, so that is something you can fix?

**Comment by nkpetko** [comment]
Yeah it is, working on it now

**Comment by nkpetko** [comment]
Has the issue occurred often or was it a one off thing? If you could also try and re-create the issue for me again that would help

**Comment by guidojw** [comment]
Yes it keeps happening, just replicated it again.

The value is 9245 characters long (excluding quotes and including value=) and the query parameter says valueLength=5361.

**Comment by nkpetko** [comment]
![image](https://user-images.githubusercontent.com/79342039/132119361-41f973b2-e38f-4ce4-ba5d-c2bab3f20c88.png)
I am struggling to reproduce it, this code here, has a value length of the same you have, 9k+
and as you can see here it is setting the value-length correctly.
![image](https://user-images.githubusercontent.com/79342039/132119411-083f7a1f-09d9-48af-a7dc-2ced3ee22bee.png)
What version of the package are you using?

Code for reference:
![image](https://user-images.githubusercontent.com/79342039/132119423-3b17423e-a917-4afb-9499-72077d2f03d9.png)

**Comment by nkpetko** [comment]
https://github.com/nkpetko/RbxDataStoreService/commit/a06555f5985929f6dd0e6a7e0a9c212a9d970986

This revision should fix your issue

**Comment by guidojw** [comment]
I'm getting an DataStore scope too long error now when not supplying a scope.
Debugged and apparently the DataStoreKeyLengthLimit (which it compares scope's length to) is 0.

**Comment by guidojw** [comment]
I think that FastLogTool is not being setup properly for me because 
1. above DataStoreKeyLengthLimit = 0
2. I still get 404s after commenting all the length checks, so it's most likely still using /persistence instead of /v1/persistence

**Comment by nkpetko** [comment]
hmm it's not loading the settings, I'll push it to npm now and see if it loads the settings then, can you also show me your "settings.json" file, because there may be some issues with it finding it, because it try catches and returns and empty object if it cannot find the file

**Comment by nkpetko** [comment]
> 2. I still get 404s after commenting all the length checks, so it's most likely still using /persistence instead of /v1/persistence

odd

**Comment by nkpetko** [comment]
Try and use this version:
```bash
$ npm i @mfd/rbxdatastoreservice@2.0.0
```

**Comment by guidojw** [comment]
Ohh the flags not being set up properly was another problem, had this yesterday too.
I'm running node in WSL and had this problem where it didn't correctly parse the settings path in `ClientSettingsTool` so I had to change the separators from \\ to /. Did that again now and that part is working.

I am now getting 404s when trying GetAsync/SetAsync.
It is sending requests to https://gamepersistence.roblox.com/v1/persistencestandard, is that correct?

**Comment by nkpetko** [comment]
There's meant to be a trailing slash what the hell, I'll also change the file paths to unix and windows supported later, I find it quite odd that the url doesn't have a trailing slash, in the settings file could you enabled FFlagFastLogEnabled and set FLogDataStore to something > 5, and check what url it is initializing the store with (should log it)

**Comment by nkpetko** [comment]
I'll look into the trailing slash issue later, trying to fix another thing right now

**Comment by nkpetko** [comment]
I am unable to reproduce the url issue, you still having it?

**Comment by guidojw** [comment]
Haven't had any time to test it since last time, will probably do later today.
Might be the same bug as with the settings path?

**Comment by guidojw** [comment]
> 
> 
> I am unable to reproduce the url issue, you still having it?

It still occurred. Did some more digging through the code and it worked after changing the last argument at https://github.com/nkpetko/RbxDataStoreService/blob/9a5387eefb7c9f6a886e8230fa8b5e9bb9202a06/src/Tools/UrlTool.ts#L169 for trimTrailingSlashes to false

**Comment by nkpetko** [comment]
Should be fixed:
`@mfd/rbxdatastoreservice@2.0.6`

**Comment by guidojw** [comment]
That version worked out of the box! Thanks for helping :)

**Comment by nkpetko** [comment]
No problem, thanks for finding the issues for me, really helped me mitigate the issues I couldn't find
