### ISSUE TITLE
Bugs in UpdateAsync

### ISSUE THREAD

**Issue by guidojw** [nkpetko/RbxDataStoreService#17]
Hi @nkpetko,
Been a long time but when I worked on this around a month ago, I found 2 more bugs:

1. https://github.com/guidojw/credits-gibber/blob/91727bebbb69a3dea2415c509303d96467bc08fc/src/commands/credits.ts#L60 if I recall correctly, this has to do with errors thrown by the runTransformFunction not being sent to the errorFunction in the UpdateAsync promise https://github.com/nkpetko/RbxDataStoreService/blob/32120df8d7b8995d92b999e97e16d89b0dedd744/Source/Classes/DataStore.ts#L480, so it hangs forever.
2. https://github.com/guidojw/credits-gibber/blob/91727bebbb69a3dea2415c509303d96467bc08fc/src/commands/credits.ts#L71 UpdateAsync returns the old instead of new data, I think result here should be r https://github.com/nkpetko/RbxDataStoreService/blob/32120df8d7b8995d92b999e97e16d89b0dedd744/Source/Classes/DataStore.ts#L166

_Originally posted by @guidojw in https://github.com/guidojw/credits-gibber/issues/1#issuecomment-944935808_

**Comment by nkpetko** [comment]
https://github.com/guidojw/credits-gibber/pull/1#issuecomment-944936685
