### ISSUE TITLE
RBLXDSS-2: Unexpected UpdateAsync result

### ISSUE THREAD

**Issue by guidojw** [nkpetko/RbxDataStoreService#88]
I initially thought GlobalDataStore.UpdateAsync returns the new updated data, but it returns

![image](https://user-images.githubusercontent.com/35309288/166250824-9f58b6ec-f6f8-4097-b6b6-ea50de361a75.png)

instead.

Is this correct?

**Comment by nkpetko** [comment]
Hello @guidojw,

Could you please supply some code to so I can better understand your issue?

**Comment by nkpetko** [comment]
Nevermind, the new-ops (v3.0.0) deployment will address 100s of issues opened across github, jira and backlog.

For now you can only really be patient and try to patch your applications to get that updated value some other way.

If I can later in the day, I will integrate a change that will fix this.
